//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatoElectations.Connector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulletin
    {
        public int BullId { get; set; }
        public int VotetFor { get; set; }
        public System.DateTime GivedDate { get; set; }
        public string SerialNum { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
