//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatoElectations.Connector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int ComID { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string PName { get; set; }
        public int Gen { get; set; }
        public int PassportNum { get; set; }
        public int IdRole { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsVoted { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual PasData PasData { get; set; }
        public virtual Role Role { get; set; }
    }
}
