//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatoElectations.Connector
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotersCurrentDisplay
    {
        public string GenName { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string PName { get; set; }
        public int Gen { get; set; }
        public int ComID { get; set; }
        public int PassportNum { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public int IdRole { get; set; }
        public int IdGen { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsVoted { get; set; }
        public int IdPas { get; set; }
        public string Serial { get; set; }
        public string Number { get; set; }
        public string Code { get; set; }
        public System.DateTime GivedDate { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string GivedPlace { get; set; }
        public string BirthPlace { get; set; }
    }
}
